### ISSUE TITLE
Consider adding complete examples that details how any additional data is retrieved.

### ISSUE THREAD

**Issue by mattssca** [morinlab/GAMBLR.data#6]
In the docs for `get_mapped_colours`, a metadata table is being called. To follow best practices guidelines, the example should also include how the user can obtain this metadata. 

In addition, consider removing the pipe, avoiding loading `dplyr` or `magrittr`. 

Also, I can not get the example to run. First, it complains about COO and EBV_status are missing and also that object `colour_codes` is not found. This is what I tested:

```
#get metadata
metadata = get_gambl_metadata()

#subset metadata on pathology
metasub = dplyr::select(metadata,
              pathology)

#get colours
GAMBLR.data::get_mapped_colours(this_df = metasub)
```

**Comment by Kdreval** [comment]
Thanks for reporting this!
I have updated the example use and made sure the new example works and illustrates how to get the metadata.
I kept dplyr since this is not the only function relying on this package so I can keep the "style" for consistency.
The fix has been implemented in [this](https://github.com/morinlab/GAMBLR.data/commit/f3f009e4ea5afcb8ff372eeeb27c844dc1db68f9) commit.
